
services:
  - type: web
    name: achievo-app
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: SECRET_KEY
        value: 9cf594e8adfc1960e62829609c486bf966f4600dce6d9b9b7a737b940495a1c4
      - key: FIREBASE_PROJECT_ID
        value: achievo-devpros
      - key: FIREBASE_AUTH_DOMAIN
        value: achievo-devpros.firebaseapp.com
      - key: FIREBASE_PRIVATE_KEY_ID
        value: your_private_key_id_here
      - key: FIREBASE_PRIVATE_KEY
        value: your_private_key_here
      - key: FIREBASE_CLIENT_EMAIL
        value: your_client_email_here
      - key: FIREBASE_CLIENT_ID
        value: your_client_id_here
      - key: FIREBASE_CLIENT_X509_CERT_URL
        value: your_cert_url_here
      - key: KOIOS_API_URL
        value: https://preprod.koios.rest/api/v1
      - key: KOIOS_API_TOKEN
        value: 
      - key: CARDANO_NETWORK
        value: preprod
      - key: PINATA_API_KEY
        value: 
      - key: PINATA_SECRET_KEY
        value: 
      - key: PINATA_JWT
        value: 
      - key: IPFS_GATEWAY
        value: https://harlequin-impressed-guan-658.mypinata.cloud/ipfs/
      - key: JWT_SECRET_KEY
        value: 
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: 3600
      - key: RATE_LIMIT_STORAGE_URL
        value: memory://
      - key: LOG_LEVEL
        value: WARNING
    autoDeploy: false
